name = "NULP Linux Minecraft"
author = "Kaspiy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42da0ece824c36f7b9846c8c8aebaaacabfb8588788d4dfad5d8437d512e179f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
