name = "NULP Linux Minecraft"
author = "Kaspiy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1763d27375b0cd0144ff12b20a82fff6378747bd5242ade42bbae70e3ec95e2"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
